version: '3'

services:
    
    postgres:
        image: 'postgres:latest'
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        # ports:
        #     - '5432:5432'
    
    server:
        build: .
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '3000:3000'
        depends_on:
            - postgres
  